version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --extra docs --frozen
    - uv run -m sphinx -T -b html -d docs/_build/doctrees -D language=en doc/source $READTHEDOCS_OUTPUT/html
