version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --extra docs
    - uv run -m sphinx -T -b html -d docs/_build/doctrees doc/source $READTHEDOCS_OUTPUT/html
