name: Publish package to PyPI

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
    - name: Build wheel
      run: |
        python setup.py sdist bdist_wheel
    - name: Test wheel
      run: |
        mkdir install_test
        cd install_test
        python -m pip install ../dist/*.whl
        python -c "import e3fp"
        cd ..
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
