name: Publish

on:
  release:
    types:
      - published

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      uv_version: "0.5.2"
      python_version: "3.12"
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.uv_version }}
      - name: Build the project
        run: uv build --no-sources --python ${{ env.python_version }}
      - name: Sync only the test dependencies
        run: uv sync --no-install-project --extras test --dev
      - name: Install and test source distribution
        run: |
          uv pip install dist/*.tar.gz
          uv run --no-sync pytest
          uv pip uninstall e3fp
      - name: Install and test wheel
        run: |
          uv pip install dist/*.whl
          uv run --no-sync pytest
      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
