name: Publish package to PyPI

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.2"
      - name: Build the project
        run: uv build --no-sources
      - name: Publish to PyPI
        run: uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
      - name: Test package installation
        run: uv run --with e3fp --no-project -- python -c "import e3fp"
